export type DefaultFeed = {
  title: string
  rssUrl: string
  category?: string
}

// Note: Many podcast hosts do not set CORS headers, which can block browser fetch
// and *always* blocks WebAudio processing of cross-origin media without CORS.
// We still include popular feeds as a starting point and surface clear errors.
export const DEFAULT_FEEDS: DefaultFeed[] = [
  { title: "A Twist of History", rssUrl: "https://rss.art19.com/a-twist-of-history" },
  { title: "The Birth Keepers | The Guardian Investigates", rssUrl: "https://www.theguardian.com/technology/series/blackbox/podcast.xml" },
  { title: "Batman: The Audio Adventures", rssUrl: "https://feeds.megaphone.fm/WMHY2708969441" },
  { title: "99% Invisible", rssUrl: "https://feeds.simplecast.com/BqbsxVfO" },
  { title: "Sleepy History", rssUrl: "https://feeds.megaphone.fm/sleepyhistory" },
  { title: "بدون ورق", rssUrl: "https://feeds.simplecast.com/_rXD2gwQ" },
  { title: "Aftermath: Hunt for the Anthrax Killer", rssUrl: "https://www.cbc.ca/podcasting/includes/aftermath.xml" },
  { title: "These Were Humans", rssUrl: "https://rss.buzzsprout.com/2165197.rss" },
  { title: "Darknet Diaries", rssUrl: "https://podcast.darknetdiaries.com" },
  { title: "The Gray Area with Sean Illing", rssUrl: "https://feeds.megaphone.fm/theezrakleinshow" },
  { title: "Strange Air", rssUrl: "https://feeds.megaphone.fm/strangeair" },
  { title: "Academy", rssUrl: "https://rss.art19.com/academy" },
  { title: "Land of the Giants", rssUrl: "https://feeds.megaphone.fm/landofthegiants" },
  { title: "The Nocturnists", rssUrl: "https://rss.libsyn.com/shows/111322/destinations/4961590.xml" },
  { title: "The Dark Is Rising", rssUrl: "https://podcasts.files.bbci.co.uk/w13xtvp7.rss" },
  { title: "Hyperfixed", rssUrl: "https://rss.pdrl.fm/d3cf31/feed.hyperfixedpod.com/" },
  { title: "Huberman Lab", rssUrl: "https://feeds.megaphone.fm/hubermanlab" },
  { title: "Criminal", rssUrl: "https://feeds.megaphone.fm/VMP7924981569" },
  { title: "Bedtime Stories", rssUrl: "https://feeds.megaphone.fm/BALLENSTUDIOS4194398857" },
  { title: "Radio Diaries", rssUrl: "https://feed.radiodiaries.org/radio-diaries" },
  { title: "The Truth", rssUrl: "http://feeds.thetruthpodcast.com/thetruthapm" },
  { title: "SCP Archives", rssUrl: "https://feeds.simplecast.com/b7dgNp7A" },
  { title: "[FEED UPDATE PERMANENTLY DISABLED] MrBallen", rssUrl: "https://podtube.me/rssfeed/UCtPrkXdtCM5DACLufB9jbsA" },
  { title: "Becoming The Main Character", rssUrl: "https://anchor.fm/s/f57dbd60/podcast/rss" },
  { title: "سوالف بزنس مع مشهور الدبيان", rssUrl: "https://files.hosting.thmanyah.com/podcasts/71/1711997528372-292/rss-feed.rss" },
  { title: "The Pragmatic Engineer", rssUrl: "https://api.substack.com/feed/podcast/458709.rss" },
  { title: "Unicorn Girl", rssUrl: "https://rss.art19.com/unicorn-girl" },
  { title: "Supercommunicators with Charles Duhigg", rssUrl: "https://feeds.acast.com/public/shows/69600ff511073a61bd6df180" },
  { title: "The Spy Who", rssUrl: "https://rss.art19.com/the-spy-who" },
  { title: "Dwarkesh Podcast", rssUrl: "https://apple.dwarkesh-podcast.workers.dev/feed.rss" },
  { title: "Fifteen: Inside the Daniel Marsh Murders", rssUrl: "https://feeds.megaphone.fm/CAD3523254036" },
  { title: "Hidden Brain", rssUrl: "https://feeds.simplecast.com/kwWc0lhf" },
  { title: "Lex Fridman Podcast", rssUrl: "https://lexfridman.com/feed/podcast/" },
  { title: "Inconceivable Truth", rssUrl: "https://feeds.simplecast.com/P2FwqleH" },
  { title: "Waveform: The MKBHD Podcast", rssUrl: "https://feeds.megaphone.fm/STU4418364045" },
  { title: "Table Read", rssUrl: "https://rss.pdrl.fm/a7a12f/rss.art19.com/table-read" },
  { title: "The Joe Rogan Experience", rssUrl: "https://feeds.megaphone.fm/GLT1412515089" },
  { title: "Bedside Rounds", rssUrl: "https://rss.libsyn.com/shows/58274/destinations/220957.xml" },
  { title: "TED Health", rssUrl: "https://feeds.acast.com/public/shows/67585b08102e6d4448d360b1" },
  { title: "The Third Angle", rssUrl: "https://rss.buzzsprout.com/1722287.rss" },
  { title: "Dirt - An Audio Drama", rssUrl: "https://feeds.megaphone.fm/dirtaudiodrama" },
  { title: "Marooned: Tales of the Catastrophically Lost", rssUrl: "https://rss.libsyn.com/shows/486009/destinations/4143459.xml" },
  { title: "This Week in Virology", rssUrl: "https://feeds.libsyn.com/21581/last100" },
  { title: "Modern Wisdom", rssUrl: "https://feeds.megaphone.fm/SIXMSB5088139739" },
  { title: "HealthyGamerGG", rssUrl: "https://feeds.megaphone.fm/NSR7100634184" },
  { title: "Tides of History", rssUrl: "https://rss.art19.com/tides-of-history" },
  { title: "Devil in the Desert", rssUrl: "https://feeds.megaphone.fm/ESP3709234327" },
  { title: "Alien Worlds", rssUrl: "https://feeds.redcircle.com/6fc617a4-40e3-4ae5-9041-0525004c0624" },
  { title: "This Week in Microbiology", rssUrl: "https://twimshow.libsyn.com/rss" },
  { title: "The Chinatown Sting", rssUrl: "https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/dfc57dfa-7eb4-4384-93a6-b336013ae711/ac433391-ed4f-49c2-b148-b336013aed5f/podcast.rss" },
  { title: "Founders", rssUrl: "https://feeds.megaphone.fm/DSLLC6297708582" },
  { title: "LeVar Burton Reads", rssUrl: "https://feeds.simplecast.com/LDNgBXht" },
  { title: "Revolutions", rssUrl: "https://revolutionspodcast.libsyn.com/rss" },
  { title: "Trap Street", rssUrl: "https://feeds.megaphone.fm/trapstreet" },
  { title: "Sherlock & Co.", rssUrl: "https://feeds.megaphone.fm/GLT1918729224" },
  { title: "If Books Could Kill", rssUrl: "https://rss.buzzsprout.com/2040953.rss" },
  { title: "The Rest Is History", rssUrl: "https://feeds.megaphone.fm/GLT4787413333" },
  { title: "Limetown", rssUrl: "https://feeds.megaphone.fm/PPY5621646923" },
  { title: "Search Engine", rssUrl: "https://feeds.megaphone.fm/search-engine" },
  { title: "The Cat In The Hat Cast", rssUrl: "https://rss.art19.com/cat-in-the-hat-cast" },
  { title: "Sherlock Holmes Short Stories", rssUrl: "https://feeds.megaphone.fm/NSR5430340583" },
  { title: "Proxy with Yowei Shaw", rssUrl: "https://feed.proxypodcast.com/" },
  { title: "On Our Watch", rssUrl: "https://feeds.megaphone.fm/KQINC9216694402" },
  { title: "How to Be a Better Human", rssUrl: "https://feeds.acast.com/public/shows/67572b3b2dd88df13220eb3b" },
  { title: "Acquired", rssUrl: "https://feeds.transistor.fm/acquired" },
  { title: "Hacking Humans", rssUrl: "https://rss.pdrl.fm/7d51b0/feeds.megaphone.fm/hacking-humans" },
  { title: "Embedded", rssUrl: "https://feeds.npr.org/510311/podcast.xml" },
  { title: "UnReality", rssUrl: "https://audioboom.com/channels/5093481.rss" },
]
